# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
# baseURL = "https://your_domain.com/"
defaultContentLanguage = "zh-cn"
languageCode = 'zh-cn'

enableRobotsTXT = true
summaryLength = 3

buildDrafts = false
buildFuture = false

enableEmoji = true

#Â googleAnalytics = "G-XXXXXXXXX"
[pagination]
  pageSize = 20

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  displayLangSwitcher = false

[services]
  [services.disqus]
    shortname = 'limou-blog'