[zh-cn]
  languageCode = "zh-cn"
  weight = 1
  title = "Limou's Site"

  [params]
  isoCode = "zh-cn"
  rtl = false
  description = "折腾，只为爱好"
  dateFormat = "2006年 1月 2日"

    [params.author]
    name = "limou"
    image = "img/avatar.png"
    headline = "折腾，只为爱好"
    bio = "无法安逸，就让不安多点意义"
