colorScheme = "one-light"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "tutorial", "posts" ]
firebase = { }
fathomAnalytics = { }
verification = { }
highlightCurrentMenuArea = true
defaultBackgroundImage = "img/background.png"
smartTOC = true
logo = "img/logo-64x64.png"
title = "Limou's Site"
dateFormat = "2006年01月02日"

[header]
layout = "background"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/tutorial"
showTaxonomies = true
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "img/background.png"

[article]
showNextPrev = true
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = true
showSummary = true

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
showHero = true
heroStyle = "background"
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = true

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"

[term]
showHero = true
heroStyle = "background"

[comments]
    provider = "disqus"
    disqusShortname = "limou-blog"

[author]
    name = "limou"
    image = "img/avatar.jpg"
    headline = "折腾，只为爱好"
    bio = "无法安逸，就让不安多点意义"